# Generated by Django 5.1.7 on 2025-07-28 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_globalsettings'),
        ('sdg_action_plan', '0003_merge_20250715_2233'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SDGFormActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('view', 'View Form'), ('edit', 'Edit Form'), ('save', 'Save Form'), ('submit', 'Submit Form'), ('export', 'Export Form')], max_length=50)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('content_length', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdg_action_plan.sdgactionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'form', 'timestamp'], name='admin_porta_user_id_e61080_idx'), models.Index(fields=['activity_type', 'timestamp'], name='admin_porta_activit_839e5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBrowserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('page_load', 'Page Load'), ('click', 'Click'), ('scroll', 'Scroll'), ('form_input', 'Form Input'), ('navigation', 'Navigation')], max_length=50)),
                ('element_id', models.CharField(blank=True, max_length=200, null=True)),
                ('element_type', models.CharField(blank=True, max_length=50, null=True)),
                ('page_url', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='admin_porta_user_id_5d0b85_idx'), models.Index(fields=['activity_type', 'timestamp'], name='admin_porta_activit_6e85ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500)),
                ('page_title', models.CharField(max_length=200)),
                ('time_spent', models.IntegerField(default=0)),
                ('visit_count', models.IntegerField(default=1)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'last_visit'], name='admin_porta_user_id_383a48_idx'), models.Index(fields=['page_url', 'last_visit'], name='admin_porta_page_ur_1707e9_idx')],
                'unique_together': {('user', 'page_url')},
            },
        ),
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.TextField()),
                ('search_type', models.CharField(choices=[('action', 'SDG Action'), ('education', 'SDG Education'), ('keyword', 'SDG Keyword'), ('general', 'General Search')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='admin_porta_user_id_1da837_idx'), models.Index(fields=['search_type', 'timestamp'], name='admin_porta_search__0e1015_idx')],
            },
        ),
    ]
